"""Metadata-driven module registry — the heart of the CRM.
Every business object is described here; API, UI, search, import/export are generated from it.
"""

F = lambda name, label_en, label_ar, type="text", **kw: dict(
    name=name, label_en=label_en, label_ar=label_ar, type=type, **kw
)

LEAD_STATUS = ["New", "Contacted", "Qualified", "Unqualified", "Converted"]
DEAL_STAGES = ["Qualification", "Needs Analysis", "Proposal", "Negotiation", "Closed Won", "Closed Lost"]
PRIORITY = ["Low", "Medium", "High", "Urgent"]

MODULES = {
    "leads": {
        "label_en": "Leads", "label_ar": "العملاء المحتملون", "icon": "🎯", "group": "sales",
        "title": "name",
        "fields": [
            F("name", "Full Name", "الاسم الكامل", required=True),
            F("company", "Company", "الشركة"),
            F("email", "Email", "البريد الإلكتروني", "email"),
            F("phone", "Phone", "الهاتف", "phone"),
            F("status", "Status", "الحالة", "select", options=LEAD_STATUS, default="New"),
            F("source", "Lead Source", "مصدر العميل", "select",
              options=["Web", "Referral", "Cold Call", "Campaign", "Partner", "Trade Show", "Other"]),
            F("rating", "Rating", "التقييم", "select", options=["Hot", "Warm", "Cold"]),
            F("industry", "Industry", "القطاع"),
            F("annual_revenue", "Annual Revenue", "الإيراد السنوي", "currency"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("city", "City", "المدينة"),
            F("country", "Country", "الدولة"),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["name", "company", "email", "phone", "status", "rating", "owner_id"],
    },
    "accounts": {
        "label_en": "Accounts", "label_ar": "الشركات", "icon": "🏢", "group": "sales",
        "title": "name",
        "fields": [
            F("name", "Account Name", "اسم الشركة", required=True),
            F("industry", "Industry", "القطاع"),
            F("type", "Type", "النوع", "select", options=["Customer", "Prospect", "Partner", "Reseller", "Vendor"]),
            F("phone", "Phone", "الهاتف", "phone"),
            F("website", "Website", "الموقع"),
            F("annual_revenue", "Annual Revenue", "الإيراد السنوي", "currency"),
            F("employees", "Employees", "عدد الموظفين", "number"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("segment", "Activity Segment", "شريحة النشاط", "select",
              options=["Platinum", "Gold", "Silver", "Bronze", "Dormant"]),
            F("list_tag", "List", "القائمة", "select",
              options=["VIP", "Loyal", "Early Adopter", "Distinguished", "Watchlist", "Blacklist"]),
            F("credit_limit", "Credit Limit", "الحد الائتماني", "currency"),
            F("blacklist_reason", "Blacklist Reason", "سبب الحظر", "textarea"),
            F("billing_address", "Billing Address", "عنوان الفوترة", "textarea"),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["name", "industry", "segment", "list_tag", "phone", "owner_id"],
    },
    "contacts": {
        "label_en": "Contacts", "label_ar": "جهات الاتصال", "icon": "👤", "group": "sales",
        "title": "name",
        "fields": [
            F("name", "Full Name", "الاسم الكامل", required=True),
            F("account_id", "Account", "الشركة", "lookup", target="accounts"),
            F("title", "Job Title", "المسمى الوظيفي"),
            F("email", "Email", "البريد الإلكتروني", "email"),
            F("phone", "Phone", "الهاتف", "phone"),
            F("mobile", "Mobile", "الجوال", "phone"),
            F("department", "Department", "القسم"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("mailing_address", "Mailing Address", "العنوان", "textarea"),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["name", "account_id", "title", "email", "phone", "owner_id"],
    },
    "deals": {
        "label_en": "Deals", "label_ar": "الصفقات", "icon": "💰", "group": "sales",
        "title": "name", "kanban": "stage",
        "fields": [
            F("name", "Deal Name", "اسم الصفقة", required=True),
            F("account_id", "Account", "الشركة", "lookup", target="accounts"),
            F("contact_id", "Contact", "جهة الاتصال", "lookup", target="contacts"),
            F("amount", "Amount", "القيمة", "currency", required=True),
            F("stage", "Stage", "المرحلة", "select", options=DEAL_STAGES, default="Qualification"),
            F("probability", "Probability %", "الاحتمالية %", "number", default=20),
            F("closing_date", "Closing Date", "تاريخ الإغلاق", "date"),
            F("source", "Source", "المصدر", "select",
              options=["Web", "Referral", "Cold Call", "Campaign", "Partner", "Other"]),
            F("campaign_id", "Campaign", "الحملة", "lookup", target="campaigns"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("next_step", "Next Step", "الخطوة التالية"),
            F("competitor_id", "Competing Against", "المنافس في الصفقة", "lookup", target="competitors"),
            F("loss_reason", "Win/Loss Reason", "سبب الفوز/الخسارة", "select",
              options=["Price", "Features", "Relationship", "Timing", "Brand", "Support", "Other"]),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["name", "account_id", "amount", "stage", "probability", "competitor_id", "owner_id"],
    },
    "opportunities": {
        "label_en": "Opportunities", "label_ar": "الفرص", "icon": "🌱", "group": "sales",
        "title": "name", "kanban": "stage",
        "fields": [
            F("name", "Opportunity", "الفرصة", required=True),
            F("account_id", "Account", "الشركة", "lookup", target="accounts"),
            F("contact_id", "Contact", "جهة الاتصال", "lookup", target="contacts"),
            F("stage", "Stage", "المرحلة", "select",
              options=["Identified", "Qualifying", "Evaluating", "Proposal",
                       "Negotiation", "Won", "Lost", "On Hold"], default="Identified"),
            F("outcome", "Outcome", "النتيجة", "select",
              options=["Potential", "Won", "Lost"], default="Potential"),
            F("value", "Estimated Value", "القيمة التقديرية", "currency", required=True),
            F("probability", "Probability %", "الاحتمالية %", "number", default=10),
            F("weighted_value", "Weighted Value", "القيمة المرجّحة", "currency"),
            F("expected_close", "Expected Close", "الإغلاق المتوقع", "date"),
            F("actual_close", "Actual Close", "الإغلاق الفعلي", "date"),
            F("source", "Source", "المصدر", "select",
              options=["Inbound", "Outbound", "Referral", "Partner", "Campaign",
                       "Existing Customer", "Tender", "Other"]),
            F("competitor_id", "Competitor", "المنافس", "lookup", target="competitors"),
            F("win_reason", "Win Reason", "سبب الفوز", "select",
              options=["Price", "Features", "Relationship", "Speed", "Support", "Brand", "Other"]),
            F("loss_reason", "Loss Reason", "سبب الخسارة", "select",
              options=["Price", "Features", "Competitor", "No Budget", "No Decision",
                       "Timing", "Lost Contact", "Other"]),
            F("deal_id", "Converted Deal", "الصفقة الناتجة", "lookup", target="deals"),
            F("next_step", "Next Step", "الخطوة التالية"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("description", "Notes", "ملاحظات", "textarea"),
        ],
        "list": ["name", "account_id", "stage", "value", "probability", "expected_close", "owner_id"],
    },
    "activities": {
        "label_en": "Activities", "label_ar": "الأنشطة", "icon": "✅", "group": "sales",
        "title": "subject",
        "fields": [
            F("subject", "Subject", "الموضوع", required=True),
            F("type", "Type", "النوع", "select", options=["Task", "Call", "Meeting", "Email"], default="Task"),
            F("status", "Status", "الحالة", "select",
              options=["Not Started", "In Progress", "Completed", "Deferred"], default="Not Started"),
            F("priority", "Priority", "الأولوية", "select", options=PRIORITY, default="Medium"),
            F("due_date", "Due Date", "تاريخ الاستحقاق", "date"),
            F("related_to", "Related To", "مرتبط بـ"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["subject", "type", "status", "priority", "due_date", "owner_id"],
    },
    "campaigns": {
        "label_en": "Campaigns", "label_ar": "الحملات التسويقية", "icon": "📣", "group": "marketing",
        "title": "name",
        "fields": [
            F("name", "Campaign Name", "اسم الحملة", required=True),
            F("type", "Type", "النوع", "select",
              options=["Email", "Webinar", "Advertisement", "Social", "Event", "Telemarketing"]),
            F("status", "Status", "الحالة", "select",
              options=["Planning", "Active", "Completed", "Paused"], default="Planning"),
            F("start_date", "Start Date", "تاريخ البدء", "date"),
            F("end_date", "End Date", "تاريخ الانتهاء", "date"),
            F("budget", "Budget", "الميزانية", "currency"),
            F("actual_cost", "Actual Cost", "التكلفة الفعلية", "currency"),
            F("expected_revenue", "Expected Revenue", "الإيراد المتوقع", "currency"),
            F("leads_generated", "Leads Generated", "العملاء المتولدون", "number"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["name", "type", "status", "start_date", "budget", "expected_revenue", "owner_id"],
    },
    "tickets": {
        "label_en": "Support Tickets", "label_ar": "تذاكر الدعم", "icon": "🎫", "group": "support",
        "title": "subject", "kanban": "status",
        "fields": [
            F("subject", "Subject", "الموضوع", required=True),
            F("account_id", "Account", "الشركة", "lookup", target="accounts"),
            F("contact_id", "Contact", "جهة الاتصال", "lookup", target="contacts"),
            F("status", "Status", "الحالة", "select",
              options=["Open", "In Progress", "Waiting on Customer", "Escalated", "Closed"], default="Open"),
            F("priority", "Priority", "الأولوية", "select", options=PRIORITY, default="Medium"),
            F("channel", "Channel", "القناة", "select", options=["Email", "Phone", "Web", "Chat", "Social"]),
            F("category", "Category", "الفئة"),
            F("due_date", "Due Date", "تاريخ الاستحقاق", "date"),
            F("owner_id", "Assigned To", "المسند إليه", "user"),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["subject", "account_id", "status", "priority", "channel", "due_date", "owner_id"],
    },
    "products": {
        "label_en": "Products", "label_ar": "المنتجات", "icon": "📦", "group": "inventory",
        "title": "name",
        "fields": [
            F("name", "Product Name", "اسم المنتج", required=True),
            F("code", "Product Code", "رمز المنتج"),
            F("category", "Category", "الفئة"),
            F("unit_price", "Unit Price", "سعر الوحدة", "currency", required=True),
            F("cost", "Cost", "التكلفة", "currency"),
            F("qty_in_stock", "Qty in Stock", "الكمية بالمخزون", "number", default=0),
            F("reorder_level", "Reorder Level", "حد إعادة الطلب", "number", default=0),
            F("tax_rate", "Tax %", "الضريبة %", "number", default=0),
            F("active", "Active", "نشط", "select", options=["Yes", "No"], default="Yes"),
            F("description", "Description", "الوصف", "textarea"),
        ],
        "list": ["name", "code", "category", "unit_price", "qty_in_stock", "active"],
    },
    "quotes": {
        "label_en": "Quotes", "label_ar": "عروض الأسعار", "icon": "📄", "group": "inventory",
        "title": "subject", "line_items": True,
        "fields": [
            F("subject", "Subject", "الموضوع", required=True),
            F("account_id", "Account", "الشركة", "lookup", target="accounts"),
            F("deal_id", "Deal", "الصفقة", "lookup", target="deals"),
            F("status", "Status", "الحالة", "select",
              options=["Draft", "Sent", "Accepted", "Rejected", "Expired"], default="Draft"),
            F("valid_until", "Valid Until", "صالح حتى", "date"),
            F("amount", "Total", "الإجمالي", "currency"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("terms", "Terms", "الشروط", "textarea"),
        ],
        "list": ["subject", "account_id", "status", "valid_until", "amount", "owner_id"],
    },
    "invoices": {
        "label_en": "Invoices", "label_ar": "الفواتير", "icon": "🧾", "group": "inventory",
        "title": "subject", "line_items": True,
        "fields": [
            F("subject", "Subject", "الموضوع", required=True),
            F("account_id", "Account", "الشركة", "lookup", target="accounts"),
            F("status", "Status", "الحالة", "select",
              options=["Draft", "Sent", "Paid", "Overdue", "Cancelled"], default="Draft"),
            F("invoice_date", "Invoice Date", "تاريخ الفاتورة", "date"),
            F("due_date", "Due Date", "تاريخ الاستحقاق", "date"),
            F("amount", "Total", "الإجمالي", "currency"),
            F("paid_amount", "Paid", "المدفوع", "currency", default=0),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("notes", "Notes", "ملاحظات", "textarea"),
        ],
        "list": ["subject", "account_id", "status", "invoice_date", "due_date", "amount", "status"],
    },
    "competitors": {
        "label_en": "Competitors", "label_ar": "المنافسون", "icon": "⚔️", "group": "intel",
        "title": "name",
        "fields": [
            F("name", "Competitor Name", "اسم المنافس", required=True),
            F("tier", "Threat Tier", "مستوى التهديد", "select",
              options=["Primary", "Secondary", "Emerging", "Niche"], default="Secondary"),
            F("segment", "Market Segment", "شريحة السوق", "select",
              options=["Enterprise", "Mid-Market", "SMB", "All"]),
            F("hq_country", "HQ Country", "بلد المقر"),
            F("website", "Website", "الموقع"),
            F("founded", "Founded", "سنة التأسيس", "number"),
            F("employees", "Employees", "عدد الموظفين", "number"),
            F("annual_revenue", "Annual Revenue", "الإيراد السنوي", "currency"),
            F("market_share", "Market Share %", "الحصة السوقية %", "number"),
            F("pricing_model", "Pricing Model", "نموذج التسعير", "select",
              options=["Subscription", "Perpetual", "Freemium", "Usage-Based", "Hybrid"]),
            F("threat_score", "Threat Score (1-10)", "درجة التهديد (١-١٠)", "number", default=5),
            F("strengths", "Strengths", "نقاط القوة", "textarea"),
            F("weaknesses", "Weaknesses", "نقاط الضعف", "textarea"),
            F("strategy", "Our Counter-Strategy", "استراتيجيتنا المضادة", "textarea"),
            F("owner_id", "Analyst", "المحلل", "user"),
        ],
        "list": ["name", "tier", "segment", "market_share", "threat_score", "pricing_model", "owner_id"],
    },
    "competitor_products": {
        "label_en": "Competitor Products", "label_ar": "منتجات المنافسين", "icon": "🧩", "group": "intel",
        "title": "name",
        "fields": [
            F("name", "Product Name", "اسم المنتج", required=True),
            F("competitor_id", "Competitor", "المنافس", "lookup", target="competitors"),
            F("category", "Category", "الفئة"),
            F("price", "List Price", "السعر المعلن", "currency"),
            F("billing", "Billing", "دورة الفوترة", "select",
              options=["Per User / Month", "Per User / Year", "Flat / Month", "One-Time", "Usage"]),
            F("target_segment", "Target Segment", "الشريحة المستهدفة", "select",
              options=["Enterprise", "Mid-Market", "SMB", "All"]),
            F("our_product_id", "Competes With", "ينافس منتجنا", "lookup", target="products"),
            F("our_price", "Our Price", "سعرنا", "currency"),
            F("positioning", "Positioning", "الموقع التنافسي", "select",
              options=["We Win", "Parity", "They Win", "Unknown"], default="Unknown"),
            F("key_features", "Key Features", "الميزات الرئيسية", "textarea"),
            F("gaps", "Feature Gaps", "الفجوات", "textarea"),
            F("owner_id", "Analyst", "المحلل", "user"),
        ],
        "list": ["name", "competitor_id", "category", "price", "our_price", "positioning", "target_segment"],
    },
    "market_research": {
        "label_en": "Market Research", "label_ar": "دراسات السوق", "icon": "🔬", "group": "intel",
        "title": "title",
        "fields": [
            F("title", "Study Title", "عنوان الدراسة", required=True),
            F("type", "Study Type", "نوع الدراسة", "select",
              options=["Market Sizing", "Competitor Analysis", "Customer Survey", "Pricing Study",
                       "SWOT", "Trend Analysis", "Win/Loss Review"]),
            F("status", "Status", "الحالة", "select",
              options=["Planned", "In Progress", "Completed", "Archived"], default="Planned"),
            F("segment", "Segment", "الشريحة", "select",
              options=["Enterprise", "Mid-Market", "SMB", "All"]),
            F("region", "Region", "المنطقة"),
            F("market_size", "Market Size (TAM)", "حجم السوق", "currency"),
            F("growth_rate", "Growth Rate %", "معدل النمو %", "number"),
            F("our_share", "Our Share %", "حصتنا %", "number"),
            F("start_date", "Start Date", "تاريخ البدء", "date"),
            F("end_date", "End Date", "تاريخ الانتهاء", "date"),
            F("budget", "Budget", "الميزانية", "currency"),
            F("source", "Source", "المصدر"),
            F("confidence", "Confidence", "درجة الثقة", "select",
              options=["High", "Medium", "Low"], default="Medium"),
            F("findings", "Key Findings", "أهم النتائج", "textarea"),
            F("recommendations", "Recommendations", "التوصيات", "textarea"),
            F("owner_id", "Researcher", "الباحث", "user"),
        ],
        "list": ["title", "type", "status", "segment", "market_size", "growth_rate", "confidence", "owner_id"],
    },
    "vendors": {
        "label_en": "Vendors", "label_ar": "الموردون", "icon": "🚚", "group": "inventory",
        "title": "name",
        "fields": [
            F("name", "Vendor Name", "اسم المورد", required=True),
            F("email", "Email", "البريد", "email"),
            F("phone", "Phone", "الهاتف", "phone"),
            F("category", "Category", "الفئة"),
            F("website", "Website", "الموقع"),
            F("owner_id", "Owner", "المسؤول", "user"),
            F("address", "Address", "العنوان", "textarea"),
        ],
        "list": ["name", "email", "phone", "category", "owner_id"],
    },
}

GROUPS = {
    "sales": {"en": "Sales", "ar": "المبيعات"},
    "marketing": {"en": "Marketing", "ar": "التسويق"},
    "support": {"en": "Support", "ar": "الدعم"},
    "inventory": {"en": "Inventory & Finance", "ar": "المخزون والمالية"},
    "intel": {"en": "Market Intelligence", "ar": "ذكاء السوق"},
}

ROLES = {
    "admin": {"en": "Administrator", "ar": "مدير النظام"},
    "manager": {"en": "Sales Manager", "ar": "مدير مبيعات"},
    "agent": {"en": "Sales Rep", "ar": "مندوب"},
    "readonly": {"en": "Read Only", "ar": "قراءة فقط"},
}
